// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {stdJson} from "forge-std/StdJson.sol";
import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {KageShieldedPool} from "../src/KageShieldedPool.sol";
import {MockERC20} from "../src/MockERC20.sol";
import {Groth16Verifier} from "../src/generated/Verifier.sol";
import {IVerifier} from "../src/interfaces/IVerifier.sol";

/// Exercises KageShieldedPool against a real Groth16 proof generated by
/// circuits/scripts/gen-contract-fixtures.mjs (test/fixtures/valid_withdraw_d1.json).
/// The fixture deposits must be replayed here in the exact same order so
/// the on-chain root matches the root the proof was generated against.
contract KageShieldedPoolTest is Test {
    using stdJson for string;

    uint256 constant D1 = 1e18;
    uint256 constant D2 = 10e18;

    KageShieldedPool pool;
    MockERC20 token;
    Groth16Verifier verifier;

    address depositor = address(0xD0);

    uint256 fixtureRoot;
    uint256 fixtureNullifierHash;
    uint256 fixtureFee;
    address fixtureRecipient;
    address fixtureRelayer;
    uint256[2] pA;
    uint256[2][2] pB;
    uint256[2] pC;

    function setUp() public {
        token = new MockERC20();
        verifier = new Groth16Verifier();

        uint256[] memory denoms = new uint256[](2);
        denoms[0] = D1;
        denoms[1] = D2;
        pool = new KageShieldedPool(IVerifier(address(verifier)), IERC20(address(token)), denoms);

        string memory json = vm.readFile("test/fixtures/valid_withdraw_d1.json");

        uint256[] memory commitmentsD1 = json.readUintArray(".commitmentsD1");
        uint256[] memory commitmentsD2 = json.readUintArray(".commitmentsD2");
        fixtureRoot = json.readUint(".root");
        fixtureNullifierHash = json.readUint(".nullifierHash");
        fixtureFee = json.readUint(".fee");
        fixtureRecipient = address(uint160(json.readUint(".recipient")));
        fixtureRelayer = address(uint160(json.readUint(".relayer")));

        uint256[] memory pAarr = json.readUintArray(".pA");
        pA = [pAarr[0], pAarr[1]];
        uint256[] memory pBflat = json.readUintArray(".pBFlat");
        pB = [[pBflat[0], pBflat[1]], [pBflat[2], pBflat[3]]];
        uint256[] memory pCarr = json.readUintArray(".pC");
        pC = [pCarr[0], pCarr[1]];

        token.mint(depositor, 1_000e18);
        vm.startPrank(depositor);
        token.approve(address(pool), type(uint256).max);
        for (uint256 i = 0; i < commitmentsD1.length; i++) {
            pool.deposit(D1, commitmentsD1[i]);
        }
        for (uint256 i = 0; i < commitmentsD2.length; i++) {
            pool.deposit(D2, commitmentsD2[i]);
        }
        vm.stopPrank();
    }

    function test_DepositMatchesFixtureRoot() public view {
        (uint256 count, uint256 root) = pool.getAnonymitySet(D1);
        assertEq(count, 3);
        assertEq(root, fixtureRoot);
    }

    function test_DepositRejectsDisallowedDenomination() public {
        vm.prank(depositor);
        vm.expectRevert("Pool: denomination not allowed");
        pool.deposit(5e18, 123);
    }

    function test_WithdrawValidPaysRecipientAndRelayer() public {
        uint256 recipientBefore = token.balanceOf(fixtureRecipient);
        uint256 relayerBefore = token.balanceOf(fixtureRelayer);

        pool.withdraw(pA, pB, pC, fixtureRoot, fixtureNullifierHash, fixtureRecipient, fixtureRelayer, fixtureFee, D1);

        assertEq(token.balanceOf(fixtureRecipient), recipientBefore + (D1 - fixtureFee));
        assertEq(token.balanceOf(fixtureRelayer), relayerBefore + fixtureFee);
        assertTrue(pool.nullifierSpent(fixtureNullifierHash));
    }

    function test_WithdrawRejectsDoubleSpend() public {
        pool.withdraw(pA, pB, pC, fixtureRoot, fixtureNullifierHash, fixtureRecipient, fixtureRelayer, fixtureFee, D1);

        vm.expectRevert("Pool: note already spent");
        pool.withdraw(pA, pB, pC, fixtureRoot, fixtureNullifierHash, fixtureRecipient, fixtureRelayer, fixtureFee, D1);
    }

    function test_WithdrawRejectsUnknownRoot() public {
        vm.expectRevert("Pool: unknown root");
        pool.withdraw(pA, pB, pC, 999, fixtureNullifierHash, fixtureRecipient, fixtureRelayer, fixtureFee, D1);
    }

    function test_WithdrawRejectsTamperedRecipient() public {
        // Proof was generated for fixtureRecipient — swapping it out must
        // invalidate the proof even though every other argument is untouched.
        vm.expectRevert("Pool: invalid proof");
        pool.withdraw(pA, pB, pC, fixtureRoot, fixtureNullifierHash, address(0xBAD), fixtureRelayer, fixtureFee, D1);
    }

    function test_WithdrawRejectsTamperedRelayer() public {
        vm.expectRevert("Pool: invalid proof");
        pool.withdraw(pA, pB, pC, fixtureRoot, fixtureNullifierHash, fixtureRecipient, address(0xBAD), fixtureFee, D1);
    }

    function test_WithdrawRejectsTamperedFee() public {
        vm.expectRevert("Pool: invalid proof");
        pool.withdraw(
            pA, pB, pC, fixtureRoot, fixtureNullifierHash, fixtureRecipient, fixtureRelayer, fixtureFee + 1, D1
        );
    }

    function test_WithdrawRejectsFeeAboveDenomination() public {
        vm.expectRevert("Pool: fee exceeds denomination");
        pool.withdraw(pA, pB, pC, fixtureRoot, fixtureNullifierHash, fixtureRecipient, fixtureRelayer, D1 + 1, D1);
    }

    function test_WithdrawRejectsSwappedDenomination() public {
        // The proof commits to amount = D1. Re-submitting it against D2
        // fails at the root-history check (D1's root isn't a known D2
        // root) — one of two independent layers (this + the circuit's own
        // `(amount-D1)*(amount-D2)===0` binding) that make denomination
        // swapping unexploitable.
        vm.expectRevert("Pool: unknown root");
        pool.withdraw(pA, pB, pC, fixtureRoot, fixtureNullifierHash, fixtureRecipient, fixtureRelayer, fixtureFee, D2);
    }
}
